export const LOADING_PHRASES = {
  general: [
    'Balancing the envelopes…',
    'Giving your money a job…',
    "Counting what's Ready to Assign…",
    "Chasing down last month's leftovers…",
    'Reconciling the chaos…',
    'Squeezing blood from the Bills envelope…',
    'Asking Rent to behave…',
    'Tallying the damage…',
    'Waking up the ledger…',
    "Making sure nothing's overspent (yet)…",
    'Checking if Groceries survived the week…',
    'Persuading Math to add up…',
    'Finding where all the money went…',
    'Teaching your budget to Budget…',
    'Begging the spending trend to flatten…',
    'Hoping the credit card behaves…',
    'Refreshing your financial reality…',
  ],
  insights: [
    'Finding where all the money went…',
    'Crunching the categories…',
    'Drawing your spending trend…',
    'Comparing this month to the last…',
    'Building the heatmap…',
    'Adding up every category…',
    'Looking for spending patterns…',
    'Lining up the months…',
  ],
  investments: [
    'Waking up your portfolio…',
    'Counting your compounding…',
    'Asking the bulls and bears to play nice…',
    'Polishing the allocation bar…',
    'Watching the SIPs do their thing…',
    'Chasing green arrows…',
    'Hoping the FDs remember their returns…',
    'Giving Gold its moment…',
    'Reminding stocks to be kind to you…',
    'Valuing your positions…',
    'Reconciling with your risk appetite…',
    'Letting the market marinate…',
    'Summoning the fund managers…',
    "Asking the index funds why you didn't buy earlier…",
  ],
  subscriptions: [
    'Counting your recurring charges…',
    'Tallying up what flows every month…',
    'Finding all the silent deductions…',
    'Mapping your subscription maze…',
    'Crunching the renewal calendar…',
    'Sorting active from cancelled…',
    'Adding up the monthly damage…',
    'Tracking where the auto-debits go…',
    'Checking which bills are due next…',
    'Calculating your commitment level…',
    'Reconciling the subscription ledger…',
    'Hunting down every recurring charge…',
    'Making sense of the billing cycles…',
    'Summing up what you actually use…',
    'Organizing your digital obligations…',
  ],
  recurringScan: [
    'Looking for repeat payments…',
    'Spotting familiar amounts…',
    'Finding the rhythm in your bills…',
    'Checking which payments keep coming back…',
    'Looking for your next regular…',
  ],
  recurring: [
    'Checking what repeats…',
    'Reading the calendar…',
    'Rounding up your regulars…',
    'Counting the usual suspects…',
    'Lining up the due dates…',
    "Working out what's next…",
    'Almost there…',
  ],
  billScans: [
    'Pulling up your scans…',
    'Sorting by date…',
    'Unfolding the receipts…',
    'Gathering your grocery runs…',
    'Finding the dinner receipts…',
    'Putting your shares in order…',
    'Rounding up the line items…',
    'Bringing the bills together…',
    'Every receipt has a story…',
    'Almost there…',
  ],
  billScanDetail: ['Pulling up this scan…', 'Almost there…'],
  scanBill: ['Reading the bill…', 'Finding the total…', 'Spotting line items…', 'Almost done…'],
  archive: ['Checking the vault…', 'Dusting off the archive…', 'Almost there…'],
  chatThinking: [
    'Thinking it through…',
    'Reading your recent transactions…',
    'Checking your envelopes…',
    'Doing the math…',
    'Putting your answer together…',
    'Looking at your spending…',
  ],
  exports: ['Loading your exports…', 'Almost there…'],
  exportBuilding: ['Packing your data…', 'Tidying the columns…', 'Almost ready…'],
  wrappedStatus: ['Checking last month…', 'Counting transactions…', 'Tallying it up…', 'Almost there…'],
} as const

export type LoadingFeature = keyof typeof LOADING_PHRASES

export const ORDERED_LOADING_FEATURES = new Set<LoadingFeature>([
  'recurring',
  'recurringScan',
  'billScans',
  'billScanDetail',
  'archive',
  'exports',
  'exportBuilding',
  'wrappedStatus',
])
