// Emits src/theme/tokens.css from src/theme/tokens.ts, so the palette is
// defined once (in the file that is a twin of Mobile's) and consumed as CSS
// custom properties everywhere else.
//
// Run: npm run gen:tokens
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')
const source = path.join(root, 'src/theme/tokens.ts')
const target = path.join(root, 'src/theme/tokens.css')

/** camelCase -> kebab-case, so `accentInk` becomes `--tk-accent-ink`. */
function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

/** Pulls one `export const <name>: ThemeTokens = { ... }` object out of the source. */
function readScheme(text, name) {
  const start = text.indexOf(`export const ${name}: ThemeTokens = {`)
  if (start === -1) throw new Error(`${name} not found in tokens.ts`)
  const open = text.indexOf('{', start)
  const close = text.indexOf('\n}', open)
  const body = text.slice(open + 1, close)
  const entries = []
  for (const line of body.split('\n')) {
    const match = line.match(/^\s*([A-Za-z0-9]+):\s*'([^']*)',?\s*$/)
    if (match) entries.push([match[1], match[2]])
  }
  if (entries.length === 0) throw new Error(`no tokens parsed from ${name}`)
  return entries
}

function block(selector, entries, indent = '  ') {
  const lines = entries.map(([name, value]) => `${indent}--tk-${kebab(name)}: ${value};`)
  return `${selector} {\n${lines.join('\n')}\n}`
}

const text = fs.readFileSync(source, 'utf8')
const dark = readScheme(text, 'darkTokens')
const light = readScheme(text, 'lightTokens')

const css = `/* GENERATED by scripts/generate-tokens.mjs from src/theme/tokens.ts.
   Do not edit — change tokens.ts and run \`npm run gen:tokens\`.

   Three theme states, matching Mobile's 'light' | 'dark' | 'system'.

   The :root pair below is what paints before the browser has resolved a
   scheme — server render and React's hydration pass, when AppShell stamps no
   theme class at all. That is why prefers-color-scheme is honoured here and
   not left to the classes: a system-light user would otherwise get a dark
   first frame. Once resolved, .theme-light / .theme-dark is authoritative
   (later in the file, so it wins at equal specificity), which also keeps the
   handful of '.theme-light .foo' rules elsewhere working under 'system'. */

:root {
${dark.map(([n, v]) => `  --tk-${kebab(n)}: ${v};`).join('\n')}
}

@media (prefers-color-scheme: light) {
${block(':root', light, '    ').split('\n').map((l) => `  ${l}`).join('\n')}
}

${block('.theme-light', light)}

${block('.theme-dark', dark)}
`

fs.writeFileSync(target, css)
console.log(`wrote ${path.relative(root, target)} (${dark.length} tokens x 2 schemes)`)
